### PR TITLE
Remove `dist` from source control

### PR DESCRIPTION
**Pull request by chrissantamaria**
Tiny PR - just removes the built `dist` directory from source control, since imo it's not particularly meaningful and can make commits a bit difficult to parse. Shouldn't affect anything on the npm distribution side.

### CODE REVIEW

**Comment by justin-hackin** [comment]
FYI, the examples reference relative paths to dist and thus will break with this PR

**Comment by chrissantamaria** [comment]
> FYI, the examples reference relative paths to dist and thus will break with this PR

Ah, interesting. I think it would just require building the main package locally before running examples, right?

If that manual build step feels cumbersome, we could also migrate to something like pnpm workspaces to more easily manage the entire build process. Might also make the examples a bit simpler to parse rather than importing the package from a relative path.

**Comment by aanckar** [comment]
I recently published a new release where I basically updated/simplified the entire build process (using `tsup` instead of `rollup`, also removed superfluous files from GitHub and npm, respectively). Improvements around building/tooling (CI, changesets etc) could still be made for sure, but considering the current scope of this library I think this is fine for now.

**Comment by chrissantamaria** [comment]
Sounds good! If you're ever interested in the workspace approach I'd be happy to take a stab at that.

**Pull request closed without merging**
